### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by buenzlidominik** [sflin/ASER_Parser#4]
Error getting method-collection

C:\temp\MethodCollections\catan.Heap`1[[T -> catan.Tile, catan]].json (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch)

Problem occured while parsing: catan.sln-contexts.zip

**Comment by buenzlidominik** [comment]
Problem is caused by special characters like <,>,?,*
Possible solution would be to simplify the name and writing the fully qualified name into the json file 
Would also be the solution for too long file names
Also there are a lot of '???' Classes. What do they stand for? Can we omit them?

**Comment by buenzlidominik** [comment]
Why does a Type declare Arguments like T -- NProxy.Core.Test.Interceptors.Types.FooBase, NProxy.Core.Test?

NProxy.Core.Interceptors.Language.ITarget`1[[T -- NProxy.Core.Test.Interceptors.Types.FooBase, NProxy.Core.Test]]

**Comment by sflin** [comment]
- issue fixed: json-files are named by declaringType().getName() (which corresponds to sort of a class) and contains a list of methodCollections. full name of methods is inside json-files
- no action considering ???-files since this is due to the data quality (but we could possibly exclude them)
